spring.application.name=weather

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.show-sql=false
spring.jpa.database=mysql

openweathermap.key=${OPENWEATHERMAP_KEY}
gemini.key=${GEMINI_KEY:}

spring.jwt.secret=${SPRING_JWT_SECRET}

logging.config=classpath:logback-spring.xml
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
